### ISSUE TITLE
About the code

### ISSUE THREAD

**Issue by Tim4Dec** [youngornever/bridge_latent_knowledge_selection_gap_for_conversation#2]
Could you release your source code or just send me a copy ?

**Comment by youngornever** [comment]
> Tim4Dec
You can find our code Here: https://pan.baidu.com/s/1f_6WFde-DNynEtq87WdYug  with Extraction code: gac9
I think it could be directly run with our *sh files.
We also provide the model checkpoint for reproduction. https://pan.baidu.com/s/1l_hG2PWD0du7wA6rxZ_z8Q with Extraction code: hqxd

I hope you find some of the code useful even if it is a mess.

**Comment by Tim4Dec** [comment]
邮件已收到。
